---
- hosts: localhost
  roles: 
    - base-networking
  vars: 
        rg_name: testrg
        cidr_address: 10.0.0.0/16
        vnet_name: testvnet
        subnet_name: testsubnet
        subnet_cidr: 10.0.0.0/24
  
