---
- hosts: localhost
  vars:
        rg_name: testrg
        cidr_address: 10.0.0.0/16
        vnet_name: testvnet
        subnet_name: testsubnet
        subnet_cidr: 10.0.0.0/24
  tasks:
    - name: complete terraform file
      template:
        src: ./variables.tf.j2
        dest: ./variables.tf
