---
- hosts: localhost
  vars:
    rg_name: testrg
    vnet_name: testvnet
    vnet_cidr: 10.0.0.0/16
    subnet_name: testsubnet
    subnet_cidr: 10.0.0.0/24
    location: uksouth
    subscription_id: 088de0df-dacc-46b9-8e67-f92a2004e935
    client_id: 289161d9-7e5e-418a-ad5a-3ff7e68daa16
    client_secret: b19ce7b7-5649-4d21-9105-7156f9b1dfe0       
    tenant_id: 152e4c75-3657-4284-bb2c-0d825873d72b
  tasks:
    - name: complete terraform file
      template:
        src: ../modules/base-networking/main.tf.j2
        dest: ../modules/base-networking/main.tf
