---
- hosts: localhost
  vars:
    rg_name: testrg
    vnet_name: testvnet
    vnet_cidr: 10.0.0.0/16
    subnet_name: testsubnet
    subnet_cidr: 10.0.0.0/24
  tasks:
    - name: complete terraform file
      template:
        src: ./variables.tf.j2
        dest: ../terraform/variables.tf
